create or replace task APRICOT_DEV_RAW.COMMON.CVI_DYNAMIC_DATA_TASK
	warehouse=DATA_COLLECTORS_PROD_WH
	schedule='USING CRON 45 * * * * America/New_York'
	as BEGIN
    CALL APRICOT_DEV_RAW.COMMON.COPY_CVI_DYNAMIC_DATA_FROM_S3();
END;

create or replace task APRICOT_DEV_RAW.COMMON.CVI_CREATE_TABLE_TASK
    warehouse=DATA_COLLECTORS_PROD_WH
    after APRICOT_DEV_RAW.COMMON.CVI_DYNAMIC_DATA_TASK
    as BEGIN
    CALL APRICOT_DEV_RAW.COMMON.CREATE_TABLE_FROM_JSON();
END;